# Generated by Django 2.2.4 on 2019-08-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='join_date',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('s', 'Secret')], default='s', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='电话'),
        ),
    ]
