# Generated by Django 2.2.4 on 2019-08-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190815_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageCode',
        ),
        migrations.DeleteModel(
            name='VerifyCode',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('s', 'Secret')], max_length=6, null=True, verbose_name='性别'),
        ),
    ]
