# Generated by Django 2.2.4 on 2019-09-17 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsCardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver')], default='G', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.PositiveIntegerField(default=0, max_length=3)),
                ('expiry_type', models.CharField(choices=[('Q', 'Quartly'), ('S', 'Semi-Annual'), ('A', 'Annual')], default='A', max_length=2)),
                ('expiry_num', models.PositiveIntegerField(default=1, max_length=3)),
                ('is_retired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointsCard',
            fields=[
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activated_date', models.DateField(blank=True, null=True)),
                ('puchased_date', models.DateTimeField(auto_now_add=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('remain_quantity', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readerpoints.PointsCardType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
