# Generated by Django 2.2.4 on 2019-09-17 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readerpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointscard',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_holder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointscard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointscardtype',
            name='expiry_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pointscardtype',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
