# Generated by Django 2.2.4 on 2019-09-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerpoints', '0002_auto_20190916_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointscard',
            name='remain_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
