# Generated by Django 2.2.3 on 2019-07-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_circulation_handled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
