# Generated by Django 2.2.3 on 2019-07-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190729_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug_hash',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
