# Generated by Django 2.2.3 on 2019-07-30 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190729_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='acquired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='memo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='retired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
