# Generated by Django 2.2.3 on 2019-07-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190729_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='call_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
