# Generated by Django 2.2.3 on 2019-07-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rating',
            new_name='ranking',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='country',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=30),
        ),
    ]
